-- CREATE TABLES & SEQUENCES ---

create sequence seq_general start with 1;
create sequence seq_BATCH start with 200;
create sequence seq_ETL start with 300;

CREATE TABLE TEST(C1 NUMBER, C2 VARCHAR2(10));

CREATE TABLE ETL_GLOBAL_CONFIG(
srno NUMBER PRIMARY KEY,
BATCH_ID NUMBER,
PARAMETER_NAME VARCHAR2(50),
PARAMETER_TYPE VARCHAR2(10),
PARAMETER_VALUE VARCHAR2(100),
PARAMETER_DESC VARCHAR2(200),
IS_VALID VARCHAR2(1),
START_DATE DATE,
END_DATE DATE
);

CREATE TABLE ETL_PROCESS_MASTER(
srno NUMBER PRIMARY KEY,
BATCH_ID NUMBER,
BATCH_SEQ_NO NUMBER(10,2),
PROCEDURE_NAME VARCHAR2(50),
PROCEDURE_TYPE VARCHAR2(20),
IS_VALID VARCHAR2(1),
START_DATE DATE,
END_DATE DATE,
DEPENDENT_BATCHID NUMBER
);


CREATE TABLE ETL_PROCESS_MASTER_log(
srno NUMBER PRIMARY KEY,
ETL_PROCESS_ID NUMBER,
BATCH_ID NUMBER,
BATCH_SEQ_NO NUMBER(10,2),
PROCEDURE_NAME VARCHAR2(50),
PROCEDURE_TYPE VARCHAR2(20),
IS_VALID VARCHAR2(1),
START_time timestamp,
END_time timestamp,
DEPENDENT_BATCHID NUMBER,
status varchar2(10),
err_msg varchar2(500),
auto_retries number,
actual_tries number
);


