INSERT INTO TEST 
SELECT 0,'A00' FROM DUAL UNION ALL 
SELECT 1,'A01' FROM DUAL UNION ALL 
SELECT 2,'A02' FROM DUAL UNION ALL 
SELECT 20,'A20' FROM DUAL   ;

  

INSERT INTO ETL_GLOBAL_CONFIG
VALUES (1,NULL, 'WAIT_TIME','NUMBER','100',NULL,'Y',SYSDATE, NULL);
INSERT INTO ETL_GLOBAL_CONFIG
VALUES (2,1001, 'PURGE','CHAR','Y','Y',NULL,SYSDATE, NULL);



INSERT INTO ETL_PROCESS_MASTER VALUES(
1, 100, 1,'PRC_TEST','ORACLE_PROCEDURE','Y',SYSDATE,NULL,NULL);
INSERT INTO ETL_PROCESS_MASTER VALUES(
2, 100, 1.1,'PRC_TEST1_1','ORACLE_PROCEDURE','Y',SYSDATE,NULL,NULL);
INSERT INTO ETL_PROCESS_MASTER VALUES(
3, 100, 2,'PRC_TEST2','ORACLE_PROCEDURE','Y',SYSDATE,NULL,NULL);
INSERT INTO ETL_PROCESS_MASTER VALUES(
4, 200, 1,'PRC_TEST','ORACLE_PROCEDURE','Y',SYSDATE,NULL,100);

commit;
